#!/bin/sh

SERVER_BIN=abducer-server-bin
CORE_BIN=abducer-server-core

SERVER_NAME="AbducerServer"
SERVER_ENDPOINTS="default -p 10000"

DIR="`pwd`/`dirname $0`"

PATH_TO_BIN="$DIR/$SERVER_BIN"

if [ ! -e "$PATH_TO_BIN" ]; then
	echo "Unable to find the server binary \`$SERVER_BIN' in"
	echo "$DIR"
	echo "--> Is the server compiled?"
	exit 1
fi

"$PATH_TO_BIN" -n "$SERVER_NAME" -e "$SERVER_ENDPOINTS" "$DIR/$CORE_BIN"
