#!/bin/sh

COLOURIZER=cat

# test presence of grcat
# (can't use `where' as it's not a sh builtin)
grcat >/dev/null 2>&1  # return code is 1 when grcat present
if [ $? -eq 1 ]; then COLOURIZER="grcat ./grc.conf"; fi

./test_abd_bm "$@" 2>&1 | $COLOURIZER
