#!/usr/bin/perl

use warnings;
use strict;

if ($#ARGV != 0) {
	print STDERR "Usage: svn-file-version FILE\n";
	exit;
}

my $file_revision = "unknown";

open(SVN_INFO, "svn status -v $ARGV[0] 2>/dev/null |") || die "Failed: $!\n";
while (<SVN_INFO>) {
	chomp;
	my $line = $_;
	if ($line =~ "^\([^ ]*\) *\([1-9][0-9]*\)") {
		$file_revision = "$2$1";
	}
}
close(SVN_INFO);


print $file_revision . "\n";
